#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if ! yarn run check-formatting; then
    yarn run format
fi

if yarn run markdownlint; then
    echo "No issues in markdown files."
fi

yarn run lint
