name: Merge to main
on:
  push:
    branches:
      - main

# trunk-ignore(checkov/CKV2_GHA_1)
permissions: write-all

jobs:
  code-quality:
    if: |
      ! cancelled() && always()
    permissions:
      # For trunk to post annotations
      checks: write
      # For repo checkout
      contents: read
    uses: climatepolicyradar/reusable-workflows/.github/workflows/node-precommit-validator.yml@v23
    with:
      node-version: 20.11.0
      package-manager: yarn

  test:
    if: |
      ! cancelled() && always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Node.js 20.11.0
        uses: actions/setup-node@v5
        with:
          node-version: 20.11.0
          cache: yarn

      - name: Install dev dependencies
        run: yarn install --production=false

      - name: Run Tests
        run: yarn test

  deploy-staging:
    needs: [code-quality, test]
    uses: ./.github/workflows/deploy-staging.yml
    secrets: inherit

  deploy-production:
    needs: [deploy-staging]
    uses: ./.github/workflows/deploy-production.yml
    secrets: inherit
